name: CyberGate
favicon: null
layout_spectrum: 0.2833942861761898
typography_spectrum: 0.5742169611621648
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#006cd1'
    - '#636363'
    - '#6ab3d7'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
